college/college/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls')),
    path('form/',include('formapp.urls')),
    #path('chaining/',include('smart-select.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

college/formapp/urls.py
from . import views
from django.urls import path

app_name='formapp'

urlpatterns = [
    path('add/',views.create_view,name='register'),
    path('ajax/load-courses/',views.load_courses,name='ajax_load_courses'),
]

college/store/urls.py
from . import views
from django.urls import path

app_name='store'
urlpatterns = [
    path('',views.allprod,name='allprod'),
    path('register/',views.register_user,name='register_user'),
    path('login/', views.login_user, name='login_user'),
    # path('form/',views.newform,name='form'),
    #path('form/',views.user_registration,name='form'),
    path('logout/',views.logout,name='logout'),
    path('submit/',views.submit_form,name='submit'),
]

college/formapp/models.py
from django.db import models

# Create your models here.
class Departments(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Courses(models.Model):
    name = models.CharField(max_length=250)
    department= models.ForeignKey(Departments, on_delete=models.CASCADE)


    def __str__(self):
        return self.name
class Registeration(models.Model):
    name=models.CharField(max_length=250)
    dob = models.DateField()
    age=models.IntegerField()
    gender=models.CharField(max_length=150,choices = [('M','Male'),('F','Female')])
    phone=models.CharField(max_length=10)
    email=models.CharField(max_length=250)
    address=models.TextField()
    department=models.ForeignKey(Departments,on_delete=models.CASCADE)
    course=models.ForeignKey(Courses,on_delete=models.CASCADE)
    purpose=models.CharField(max_length=3,choices=(('R','Return'),('E','Exchange'),('O','Place Order')))
    materials=models.BooleanField(max_length=150,blank = True)

college/store/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    name=models.CharField(max_length=250,unique=True)
    desc=models.TextField()
    img=models.ImageField(upload_to='pics')
    price=models.DecimalField(max_digits=5,decimal_places=2)
    stock=models.IntegerField()
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        db_table='Items'
        ordering=['created']

    def __str__(self):
        return self.name

college/formapp/forms.py
from django import forms
from . models import Registeration,Courses

class RegisterForm(forms.ModelForm):
    class Meta:
        model=Registeration
        fields = '__all__'
        widgets = {'dob': forms.DateInput(attrs={'type': 'date'}),
                    'gender': forms.RadioSelect(),
                  'materials':forms.CheckboxSelectMultiple(choices=(('chart','Chart Paper'),('files','Files'),('pencil','Pencil'),('note','Notebook'),('pen','Pen'),('exam','Exam Papers')))
                    }
#'materials':forms.CheckboxSelectMultiple


    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        self.fields['course'].queryset = Courses.objects.none()


        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Courses.objects.filter(department_id=department_id).order_by('name')

            except(ValueError , TypeError):
                pass

        elif self.instance.pk:
            self.fields['course'].queryset= self.instance.department.course_set.order_by('name')

college/formapp/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from .models import Courses
# Create your views here.
def create_view(request):
    form = RegisterForm()

    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('store:submit')
    return render(request,'registerform.html',{'form':form})

def load_courses(request):
    department_id = request.GET.get('department_id')
    courses = Courses.objects.filter(department_id=department_id)
    return render(request,'courses_dropdown.html',{'courses':courses})

college/store/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Item
# Create your views here.

def allprod(request):
    obj = Item.objects.all()
    return render(request,'home.html',{'prod':obj})

def register_user(request):

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        c_password = request.POST['password1']
        try:
            if password == c_password:
                # if User.objects.filter(username=username).exists():
                #     messages.info(request, "Username Taken")
                #     return redirect('register_user')
                user = User.objects.create_user(username=username, password=password)
                user.save()
                return redirect('store:login_user')

            # else:
            #     messages.info(request, "Password Not Matching")
            #     return redirect('register_user')
        except Exception as e:
            return redirect('store:register_user')

    return render(request, 'register.html')

def login_user(request):

        if request.method=='POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            # username=request.POST['username']
            # password = request.POST['password']
            user=auth.authenticate(username=username,password=password)

            if user is not None:
                auth.login(request,user)
                return render(request,'button.html')

            else:
                messages.info(request,"invalid credentials")
                return redirect('store:login_user')

        return render(request,'login.html')



def logout(request):
    auth.logout(request)
    return redirect('/')

# def newform(request):
#     return render(request,'newform.html')


def submit_form(request):
    return render(request,'submit.html')

college/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>-->
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static '/js/popper.min.js' %}" ></script>
<script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>

college/templates/button.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color:Moccasin;text-align:center;padding:80px;">
<form action="{% url 'formapp:register' %}" method="post">
{% csrf_token %}
 <button type="submit" name='mybtn' >Fill the Form</button>
 </form>
<!--<form>-->
<!--    <button type="button"class="btn btn-success">Click Me</button>-->
<!--</form>-->
</body>
</html>

college/templates/course_dropdown.html
 <label class="required" for="course" >Course:</label>

    <select name="course" id="course" class="course-dropdown">
        <option selected>--Select Courses--</option>
            {% for course in courses %}
                 <option value="{{course.id}}">{{course.name}}</option>
            {% endfor %}
    </select>

college/templates/courses_dropdown.html
<option value="">--------</option>
{% for i in courses %}
    <option value="{{i.pk}}"> {{i.name}} </option>
{% endfor %}

college/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center"> &copy; Global College Pvt Ltd .All rights Reserved</p>
</div>

college/templates/header.html
{% load static %}
<header>
    <center>
       <a href="{% url 'store:allprod' %}"><img src="{% static '/img/logo.png' %}"  width="150px;" height="180px;"></a>
    </center>
</header>

college/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}
 Welcome to our Online Store....
{% endblock %}

{% block title %}
     Welcome to our Online Store....
{% endblock %}

{% block content %}

<div>
    <div class="row my_row" style="padding :30px;">
    <h1 class="text-center my_title"> Welcome to our Store....</h1>
    </div>
</div>

<div class="container">
    <div class="row mx_auto">
    {% for prod in prod %}
        <div class="my_bottom-margin col-9 col-sm-12  col-md-4 col-lg-4"  style="padding:10px;">
            <div class="card text-center" style="min-width: 18rem;">
                <img class="card-img-top my_image" src ="{{ prod.img.url }}" alt="{{prod.name}}" style="max-height:250px;">
            <div class="card-body">
                <h4> {{ prod.name }} </h4>
                <p> {{ prod.price }} </p>
            </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

college/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body style="background-color:Moccasin;text-align:center;padding:80px;">
<form action="{% url 'store:login_user' %}" method="post">
    <h1 class="text-center">Login</h1>
  {% csrf_token %}
  <input type="text" name="username" placeholder="Enter Your Username"><br>
    <br>
  <input type="password" name="password" placeholder="Enter Your Password"><br>
    <br>
  <input type="submit">
    <br>
    <br>
    <br>
    <a href="{% url 'store:register_user' %}">Register</a>
</form>
</body>
</html>

college/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item" >
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item dropdown" >
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
          Department
            </a>
          <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Science">Science</a></li>
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Computer_science">Computer Science</a></li>
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Commerce">Commerce</a></li>
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Humanities">Humanities</a></li>
                <li><a class="dropdown-item" href="https://en.wikipedia.org/wiki/Language_and_Literature">Language & Literature</a></li>
          </ul>
            </li>
          <li class="nav-item">
          <a class="nav-link " href="{% url 'store:register_user' %}">Register</a>
        </li>
   </ul>
       {% if user.is_authenticated %}
        <b> Hello {{user.username}}</b><br>

        <a href="{% url 'store:logout' %}"><button class="btn btn-outline-success" type="submit" >Logout</button></a>
      {% else %}
        <a href="{% url 'store:login_user' %}"><button class="btn btn-outline-success" type="submit">Login</button></a>
      {% endif %}
    </div>
  </div>
</nav>

college/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body style="background-color:Moccasin;text-align:center;padding:80px;">
<h1> Register </h1>
<Form method="post" action="{% url 'store:register_user' %}">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username"><br>
    <br>
    <input type="password" name="password" placeholder="Password"><br>
    <br>
    <input type="password" name="password1" placeholder="Confirm Password"><br>
    <br>
    <input type="submit">

</Form>
</body>
</html>

college/templates/registerform.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
   <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <style>
        body{
        background-color:Moccasin;
            padding:50px;
            }
        body label{
            padding:10px;
            text-align:center;
        }

</style>
</head>
<body>
<h1>Registration Form</h1>
<form method="post" id="RegisterForm" data-courses-url="{% url 'formapp:ajax_load_courses' %}" class="form-horizontal" role="form">
    {% csrf_token %}
        {{form.as_p}}
    <input type="submit" value="Submit" class="btn btn-info">
</form>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js"></script>
<script>
    $("#id_department").change(function() {
        const url = $("#RegisterForm").attr("data-courses-url");
        const departmentId= $(this).val();

        $.ajax({
            url: url,
            data: {
                'department_id' : departmentId
            },
            success : function(data){
                $("#id_course").html(data);
            }
        });
    });

</script>
</body>
</html>

college/templates/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
</head>
<body>
<form>
    <h1>Your Order Confirmed</h1>
    <a href="{% url 'store:allprod' %}">Home</a>
</form>
</body>
</html>